"""Jupyter Notebook export — generates .ipynb from an ExecutionPlan.

Uses nbformat to produce valid Jupyter notebooks that reproduce pipeline
execution outside Blueprint.  Each block gets a markdown description cell
and a code cell that imports run.py and creates a BlockContext with the
exact resolved config from the planner.

Blocks whose output ports declare ``data_type: "metrics"`` in their
``block.yaml`` automatically get an inline matplotlib visualization cell.

Risk mitigations (prompt 2.4):

1. **nbformat dependency** — imported lazily; a clear ``ImportError`` is
   raised at call time if the package is missing, not at module import.
2. **Dependency resolution** — uses ``export_dependencies.py`` (authoritative
   backend mirror of the frontend's ``BLOCK_DEPENDENCIES`` map) instead of
   scanning for per-block ``requirements.txt`` files (which don't exist).
3. **Metrics detection** — queries ``block.yaml`` output port ``data_type``
   via the block registry instead of name-guessing heuristics.
4. **Portable paths** — generated code resolves block directories relative
   to the notebook's own directory first (``./blocks/<category>/<type>/``),
   falling back to the absolute path only if the relative copy doesn't exist.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .executor import _find_block_module
from .export_dependencies import collect_pip_dependencies_for_plan
from ..config import BUILTIN_BLOCKS_DIR

if TYPE_CHECKING:
    from .planner_models import ExecutionPlan

logger = logging.getLogger("blueprint.jupyter_export")


def _require_nbformat():
    """Lazily import nbformat with a clear error if missing."""
    try:
        import nbformat
        return nbformat
    except ImportError:
        raise ImportError(
            "The 'nbformat' package is required for Jupyter notebook export. "
            "Install it with: pip install 'nbformat>=5.9.0'"
        ) from None


def _block_has_metrics_output(block_type: str) -> bool:
    """Check if a block has any output port with data_type == 'metrics'.

    Queries the block registry (block.yaml) for the authoritative answer
    instead of guessing from block type names or categories.
    """
    from .block_registry import get_block_yaml

    schema = get_block_yaml(block_type)
    if not schema:
        return False

    outputs = schema.get("outputs", [])
    for port in outputs:
        if isinstance(port, dict) and port.get("data_type") == "metrics":
            return True
        # Also check aliases — some blocks alias their metrics port
        aliases = port.get("aliases", []) if isinstance(port, dict) else []
        if any(a == "metrics" for a in aliases):
            return True

    return False


def _block_relative_path(block_type: str) -> str | None:
    """Return the category/block_type relative path for a block, or None."""
    from .block_registry import get_block_yaml

    schema = get_block_yaml(block_type)
    if not schema:
        return None
    category = schema.get("category", "")
    if not category:
        return None
    return f"{category}/{block_type}"


def compile_pipeline_to_jupyter(
    pipeline_name: str,
    plan: ExecutionPlan,
    edges: list[dict],
    nodes: list[dict],
    description: str = "",
) -> Any:
    """Generate a Jupyter notebook (.ipynb) from an ExecutionPlan.

    Returns the notebook as an nbformat NotebookNode that can be
    serialized with ``nbformat.writes()`` or ``json.dumps()``.

    Parameters
    ----------
    pipeline_name : str
        Human-readable pipeline name.
    plan : ExecutionPlan
        Frozen execution plan from the planner.
    edges : list[dict]
        Raw pipeline edges.
    nodes : list[dict]
        Raw pipeline nodes.
    description : str, optional
        Pipeline description.

    Raises
    ------
    ImportError
        If ``nbformat`` is not installed.
    """
    nbformat = _require_nbformat()
    from .block_registry import resolve_output_handle

    nb = nbformat.v4.new_notebook()
    nb.metadata["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    node_map = {n["id"]: n for n in nodes}

    # ── Cell 1: Header markdown ──
    header_lines = [
        f"# {pipeline_name}",
        "",
        f"**Generated by Blueprint** (plan: `{plan.plan_hash}`)",
        f"**Generated:** {timestamp}",
    ]
    if description:
        header_lines.extend(["", description])
    header_lines.extend([
        "",
        "---",
        "",
        "This notebook reproduces the pipeline execution outside Blueprint.",
        "Block execution order and resolved configs match the in-app executor.",
        "",
        "**Limitations:**",
        "- No SSE progress events",
        "- No artifact storage integration",
        "- No partial rerun support",
        "",
        "**Portability:** Block code is loaded from `./blocks/<category>/<type>/run.py` ",
        "relative to this notebook. If not found, the original absolute path is used as ",
        "fallback. To make this notebook fully portable, copy the `blocks/` directory ",
        "alongside it (use the 'bundle' export option for an automatic zip).",
    ])
    nb.cells.append(nbformat.v4.new_markdown_cell("\n".join(header_lines)))

    # ── Cell 2: pip install dependencies ──
    pip_deps = collect_pip_dependencies_for_plan(plan)
    install_lines = [
        "# Install required dependencies",
        "import subprocess, sys",
        "",
    ]
    if pip_deps:
        deps_str = ", ".join(f'"{d}"' for d in pip_deps)
        install_lines.append(
            f"subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', {deps_str}])"
        )
    else:
        install_lines.append("# No additional pip dependencies detected for these blocks.")
    nb.cells.append(nbformat.v4.new_code_cell("\n".join(install_lines)))

    # ── Cell 3: Setup (BlockContext, helpers, path resolution) ──
    blocks_parent = str(BUILTIN_BLOCKS_DIR.parent)
    setup_code = f'''import os
import sys
import uuid
import json
import importlib.util
from pathlib import Path
from typing import Any

# ── Path resolution ─────────────────────────────────────────
# Prefer blocks relative to this notebook; fall back to absolute.
_NOTEBOOK_DIR = Path(os.path.abspath('')).resolve()
_BLOCKS_PARENT_ABS = Path(r'{blocks_parent}')

def _resolve_block_dir(relative_path: str, absolute_path: str) -> str:
    """Return the block directory, preferring the portable relative copy."""
    local = _NOTEBOOK_DIR / 'blocks' / relative_path
    if local.is_dir() and (local / 'run.py').exists():
        return str(local)
    if _BLOCKS_PARENT_ABS.is_dir() and _BLOCKS_PARENT_ABS not in [Path(p) for p in sys.path]:
        sys.path.insert(0, str(_BLOCKS_PARENT_ABS))
    return absolute_path

class BlockContext:
    """Minimal BlockContext for exported execution."""
    def __init__(self, run_dir, block_dir, config, inputs, project_name='', experiment_name=''):
        self.run_dir = run_dir
        self.block_dir = block_dir
        self.config = config
        self.inputs = inputs
        self._inputs = inputs
        self.project_name = project_name
        self.experiment_name = experiment_name
        self._outputs = {{}}
        self._metrics = {{}}
        os.makedirs(run_dir, exist_ok=True)
    def load_input(self, name):
        if name not in self.inputs:
            raise ValueError(f"Input '{{name}}' not connected")
        return self.inputs[name]
    def log_message(self, msg): print(f"  [LOG] {{msg}}")
    def log_metric(self, name, value, step=None):
        self._metrics[name] = value
        print(f"  [METRIC] {{name}} = {{value}}")
    def report_progress(self, current, total):
        pct = int(current / total * 100) if total > 0 else 0
        print(f"  [PROGRESS] {{pct}}% ({{current}}/{{total}})")
    def save_output(self, name, data): self._outputs[name] = data
    def save_artifact(self, name, path): print(f"  [ARTIFACT] {{name}} -> {{path}}")
    def get_outputs(self): return self._outputs
    def get_metrics(self): return self._metrics

def load_block_run_function(block_dir):
    run_py = os.path.join(block_dir, 'run.py')
    if not os.path.exists(run_py):
        raise FileNotFoundError(f'Block run.py not found at {{run_py}}')
    # Add block's parent to sys.path for cross-block imports
    block_parent = str(Path(block_dir).parent.parent)
    if block_parent not in sys.path:
        sys.path.insert(0, block_parent)
    spec = importlib.util.spec_from_file_location('block_module', run_py)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.run

# Shared state
run_id = str(uuid.uuid4())
base_run_dir = os.path.join(os.getcwd(), 'artifacts', run_id)
outputs = {{}}
print(f"Run ID: {{run_id}}")
print(f"Artifacts: {{base_run_dir}}")'''
    nb.cells.append(nbformat.v4.new_code_cell(setup_code))

    # ── Per-block cells ──
    block_idx = 0
    for node_id in plan.execution_order:
        resolved = plan.nodes.get(node_id)
        if not resolved:
            continue

        node = node_map.get(node_id, {})
        node_data = node.get("data", {})
        label = node_data.get("label", resolved.block_type)
        block_type = resolved.block_type
        block_version = resolved.block_version
        category = node_data.get("category", "")
        config = resolved.resolved_config

        block_dir = _find_block_module(block_type)
        if not block_dir:
            nb.cells.append(nbformat.v4.new_markdown_cell(
                f"### Block: {label}\n\n"
                f"**Type:** `{block_type}` (v{block_version})\n\n"
                f"**SKIPPED** — `run.py` not found on this machine."
            ))
            continue

        block_idx += 1
        relative_path = _block_relative_path(block_type)

        # Config summary for the markdown cell
        config_summary_lines = []
        for key, val in config.items():
            val_str = json.dumps(val) if not isinstance(val, str) else val
            if len(val_str) > 80:
                val_str = val_str[:77] + "..."
            config_summary_lines.append(f"- `{key}`: {val_str}")
        config_summary = "\n".join(config_summary_lines) if config_summary_lines else "*(no config)*"

        # Markdown description cell
        md_lines = [
            f"### Block {block_idx}: {label}",
            "",
            f"**Type:** `{block_type}` (v{block_version})",
        ]
        if category:
            md_lines.append(f"**Category:** {category}")
        md_lines.extend([
            "",
            "**Resolved Config:**",
            config_summary,
        ])
        nb.cells.append(nbformat.v4.new_markdown_cell("\n".join(md_lines)))

        # Code execution cell
        safe_id = f"node_{node_id.replace('-', '_')}"
        block_dir_str = str(block_dir).replace('\\', '\\\\')
        config_json = json.dumps(config, indent=2)

        code_lines = [
            f"# Block {block_idx}: {label} ({block_type})",
        ]

        # Resolve block directory (relative preferred, absolute fallback)
        if relative_path:
            code_lines.append(
                f"block_dir_{safe_id} = _resolve_block_dir({json.dumps(relative_path)}, r'{block_dir_str}')"
            )
        else:
            code_lines.append(f"block_dir_{safe_id} = r'{block_dir_str}'")

        code_lines.append(f"inputs_{safe_id} = {{}}")

        # Wire inputs from edges
        edges_by_handle: dict[str, list[dict]] = {}
        for edge in edges:
            if edge.get("target") == node_id:
                tgt_handle = edge.get("targetHandle", "")
                if tgt_handle not in edges_by_handle:
                    edges_by_handle[tgt_handle] = []
                edges_by_handle[tgt_handle].append(edge)

        for tgt_handle, handle_edges in edges_by_handle.items():
            if len(handle_edges) == 1:
                edge = handle_edges[0]
                src_id = edge.get("source", "")
                src_handle = edge.get("sourceHandle", "")
                safe_src_id = f"node_{src_id.replace('-', '_')}"

                src_node = node_map.get(src_id)
                if src_node:
                    src_block_type = src_node.get("data", {}).get("type", src_node.get("type", ""))
                    src_handle = resolve_output_handle(src_block_type, src_handle)

                code_lines.append(f"if '{src_handle}' in outputs.get('{safe_src_id}', {{}}):")
                code_lines.append(f"    inputs_{safe_id}['{tgt_handle}'] = outputs['{safe_src_id}']['{src_handle}']")
            else:
                code_lines.append(f"_multi = []")
                for edge in handle_edges:
                    src_id = edge.get("source", "")
                    src_handle = edge.get("sourceHandle", "")
                    safe_src_id = f"node_{src_id.replace('-', '_')}"
                    src_node = node_map.get(src_id)
                    if src_node:
                        src_block_type = src_node.get("data", {}).get("type", src_node.get("type", ""))
                        src_handle = resolve_output_handle(src_block_type, src_handle)
                    code_lines.append(f"if '{src_handle}' in outputs.get('{safe_src_id}', {{}}):")
                    code_lines.append(f"    _multi.append(outputs['{safe_src_id}']['{src_handle}'])")
                code_lines.append(f"if _multi:")
                code_lines.append(f"    inputs_{safe_id}['{tgt_handle}'] = _multi")

        code_lines.extend([
            "",
            f"ctx_{safe_id} = BlockContext(",
            f"    run_dir=os.path.join(base_run_dir, '{node_id}'),",
            f"    block_dir=block_dir_{safe_id},",
            f"    config=json.loads({json.dumps(config_json)}),",
            f"    inputs=inputs_{safe_id},",
            f")",
            f"run_fn = load_block_run_function(block_dir_{safe_id})",
            f"run_fn(ctx_{safe_id})",
            f"outputs['{safe_id}'] = ctx_{safe_id}.get_outputs()",
            f"print(f'Completed: {label} — outputs: {{list(ctx_{safe_id}.get_outputs().keys())}}')",
        ])
        nb.cells.append(nbformat.v4.new_code_cell("\n".join(code_lines)))

        # Metrics visualization cell — only for blocks with metrics output ports
        if _block_has_metrics_output(block_type):
            viz_code = f"""# Visualize metrics from: {label}
metrics = ctx_{safe_id}.get_metrics()
if metrics:
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(8, 4))
    names = list(metrics.keys())
    values = [float(v) if isinstance(v, (int, float)) else 0 for v in metrics.values()]
    ax.barh(names, values, color='#00BFA5')
    ax.set_xlabel('Value')
    ax.set_title('{label} — Metrics')
    plt.tight_layout()
    plt.show()
else:
    print('No metrics recorded by this block.')"""
            nb.cells.append(nbformat.v4.new_code_cell(viz_code))

    # Validate the notebook
    nbformat.validate(nb)

    return nb


def notebook_to_json(nb: Any) -> str:
    """Serialize a notebook object to JSON string."""
    nbformat = _require_nbformat()
    return nbformat.writes(nb)
