#!/bin/bash
# ──────────────────────────────────────────────────────────────
#  Fix Blueprint.app and Model Manager.app launchers
#  Requires sudo to modify files in /Applications
#
#  Usage:  sudo bash fix-app-launchers.sh
# ──────────────────────────────────────────────────────────────

set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Fix 1: Blueprint.app ─────────────────────────────────────
# Problem: macOS TCC blocks unsigned .app from executing scripts
# in ~/Desktop — causes "Operation not permitted".
# Fix: Read launch.sh content via cat and pipe to bash instead
# of directly invoking the file.

BLUEPRINT_LAUNCHER="/Applications/Blueprint.app/Contents/MacOS/blueprint-launcher"

if [ -f "$BLUEPRINT_LAUNCHER" ]; then
    echo -e "${CYAN}Fixing Blueprint.app launcher...${NC}"

    # Replace the direct bash invocation with cat-pipe approach
    sed -i '' \
        's|SCRIPT_DIR="\$REPO_ROOT" bash "\$LAUNCH_SCRIPT"|export SCRIPT_DIR="$REPO_ROOT"\n/bin/bash -c "$(cat "$LAUNCH_SCRIPT")"|' \
        "$BLUEPRINT_LAUNCHER" 2>/dev/null

    # If sed didn't work (pattern already changed or different), write the full fixed file
    if grep -q 'bash "\$LAUNCH_SCRIPT"' "$BLUEPRINT_LAUNCHER" 2>/dev/null; then
        echo -e "${RED}sed replacement didn't match, writing full launcher...${NC}"
    fi

    # Safer approach: write the entire fixed launcher
    cat > "$BLUEPRINT_LAUNCHER" << 'LAUNCHER'
#!/bin/bash
# Blueprint Dev Launcher
# Launched by macOS when you double-click Blueprint.app
# Generated by make-dev-app.sh — repo path embedded at build time.

# macOS GUI apps do NOT inherit your terminal PATH.
# We must set it up manually so python3 and node are found.
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

# Source shell profiles for any custom PATH additions
[ -f "$HOME/.zprofile" ]     && source "$HOME/.zprofile"     2>/dev/null || true
[ -f "$HOME/.zshrc" ]        && source "$HOME/.zshrc"        2>/dev/null || true
[ -f "$HOME/.bash_profile" ] && source "$HOME/.bash_profile" 2>/dev/null || true
[ -f "$HOME/.profile" ]      && source "$HOME/.profile"      2>/dev/null || true

# Absolute path to the Blueprint repo (embedded at generation time)
REPO_ROOT="/Users/santiagoaraoz/Desktop/blueprint"
LAUNCH_SCRIPT="$REPO_ROOT/launch.sh"

# ── Check if Blueprint is already running ─────────────────────
BACKEND_PORT=8000
FRONTEND_PORT=4174

backend_up=false
frontend_up=false

if curl -s "http://127.0.0.1:$BACKEND_PORT/api/health" >/dev/null 2>&1; then
    backend_up=true
fi
if curl -s "http://127.0.0.1:$FRONTEND_PORT" >/dev/null 2>&1; then
    frontend_up=true
fi

if [ "$backend_up" = true ] && [ "$frontend_up" = true ]; then
    osascript -e 'display notification "Blueprint is already running — opening browser." with title "Blueprint"' 2>/dev/null || true
    open "http://localhost:$FRONTEND_PORT"
    exit 0
fi

# ── Validate launch.sh exists in repo ─────────────────────────
if [ ! -f "$LAUNCH_SCRIPT" ]; then
    osascript -e "display alert \"Blueprint Error\" message \"Cannot find launch.sh at $LAUNCH_SCRIPT. Is the repo still at this location?\" as critical" 2>/dev/null
    exit 1
fi

# ── Set up logging ────────────────────────────────────────────
LOG_DIR="$HOME/.blueprint"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/launch.log"

echo "" >> "$LOG_FILE"
echo "──── Blueprint launched at $(date) ────" >> "$LOG_FILE"

# Show a notification that we're starting
osascript -e 'display notification "Starting backend and frontend..." with title "Blueprint" sound name "default"' 2>/dev/null || true

# ── Launch Blueprint ──────────────────────────────────────────
# Read launch.sh content and execute it inline to avoid macOS TCC
# "Operation not permitted" errors that block .app bundles from
# directly executing scripts in ~/Desktop or other protected folders.
# Updates to launch.sh still take effect without rebuilding the .app.
cd "$REPO_ROOT"
export SCRIPT_DIR="$REPO_ROOT"
/bin/bash -c "$(cat "$LAUNCH_SCRIPT")" >> "$LOG_FILE" 2>&1
EXIT_CODE=$?

# ── Show error alert if launch failed ─────────────────────────
if [ $EXIT_CODE -ne 0 ]; then
    osascript -e "display alert \"Blueprint Failed\" message \"Blueprint exited with an error. Check the log at ~/.blueprint/launch.log for details.\" as critical" 2>/dev/null
fi
LAUNCHER

    chmod +x "$BLUEPRINT_LAUNCHER"
    xattr -cr "/Applications/Blueprint.app" 2>/dev/null || true
    echo -e "${GREEN}Blueprint.app fixed!${NC}"
else
    echo -e "${RED}Blueprint.app not found in /Applications${NC}"
fi

echo ""

# ── Fix 2: Model Manager.app ─────────────────────────────────
# Problem 1: PATH is set AFTER streamlit detection, so `which`
#   can't find it in the .app's minimal environment.
# Problem 2: APP_DIR points to ~/Desktop/model-manager (empty)
#   instead of /Applications/model-manager (has actual code).
# Fix: Move PATH setup before detection, fix APP_DIR path.

MM_LAUNCHER="/Applications/Model Manager.app/Contents/MacOS/ModelManager"

if [ -f "$MM_LAUNCHER" ]; then
    echo -e "${CYAN}Fixing Model Manager.app launcher...${NC}"

    cat > "$MM_LAUNCHER" << 'LAUNCHER'
#!/bin/bash
# Model Manager — Launch Streamlit Dashboard
# Explicit paths for macOS .app bundle environment

# macOS GUI apps do NOT inherit your terminal PATH.
# Set PATH BEFORE detecting streamlit so `which` can find it.
export PATH="/Library/Frameworks/Python.framework/Versions/3.12/bin:$HOME/Library/Python/3.12/bin:$HOME/.npm-global/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

# Source shell profiles for any custom PATH additions
[ -f "$HOME/.zprofile" ]     && source "$HOME/.zprofile"     2>/dev/null || true
[ -f "$HOME/.zshrc" ]        && source "$HOME/.zshrc"        2>/dev/null || true
[ -f "$HOME/.bash_profile" ] && source "$HOME/.bash_profile" 2>/dev/null || true

export OLLAMA_MODELS="/Volumes/Cold Storage 1/models/ollama"

STREAMLIT="/Library/Frameworks/Python.framework/Versions/3.12/bin/streamlit"
if [ ! -f "$STREAMLIT" ]; then
    STREAMLIT="$HOME/Library/Python/3.12/bin/streamlit"
fi
if [ ! -f "$STREAMLIT" ]; then
    STREAMLIT=$(which streamlit 2>/dev/null)
fi

if [ -z "$STREAMLIT" ] || [ ! -f "$STREAMLIT" ]; then
    osascript -e 'display alert "Model Manager Error" message "Cannot find streamlit. Install it with: pip3 install streamlit" as critical' 2>/dev/null
    exit 1
fi

APP_DIR="/Applications/model-manager"
LOG_FILE="$APP_DIR/model-manager.log"
PORT=8501

# Check if already running
if curl -sf "http://localhost:$PORT" >/dev/null 2>&1; then
    open "http://localhost:$PORT"
    exit 0
fi

# Start Streamlit
cd "$APP_DIR"
"$STREAMLIT" run frontend/app.py \
    --server.port "$PORT" \
    --server.headless true \
    --browser.gatherUsageStats false \
    >> "$LOG_FILE" 2>&1 &

# Wait for server
for i in {1..20}; do
    if curl -sf "http://localhost:$PORT" >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

open "http://localhost:$PORT"
LAUNCHER

    chmod +x "$MM_LAUNCHER"
    xattr -cr "/Applications/Model Manager.app" 2>/dev/null || true
    echo -e "${GREEN}Model Manager.app fixed!${NC}"
else
    echo -e "${RED}Model Manager.app not found in /Applications${NC}"
fi

echo ""
echo -e "${GREEN}Done! Both apps should now launch correctly.${NC}"
echo -e "  Try opening them from Launchpad or Spotlight."
