#!/bin/bash
# ──────────────────────────────────────────────────────────────
#  Generate Blueprint.app — a double-clickable macOS launcher
#  that wraps launch.sh so you never need to open a terminal.
#
#  Usage:  bash make-dev-app.sh
#  Result: Blueprint.app installed to /Applications
#
#  How it works: the .app delegates to Terminal.app via osascript
#  so that launch.sh runs with the user's normal file-access
#  permissions. Direct execution from an .app bundle is blocked
#  by macOS sandbox for TCC-protected paths like ~/Desktop.
# ──────────────────────────────────────────────────────────────

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="Blueprint"
APP_DIR="$SCRIPT_DIR/$APP_NAME.app"

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
DIM='\033[0;90m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo -e "${CYAN}Creating $APP_NAME.app...${NC}"

# Clean previous build
rm -rf "$APP_DIR"

# Create .app directory structure
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

# ── Info.plist ────────────────────────────────────────────────

cat > "$APP_DIR/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Blueprint</string>
    <key>CFBundleDisplayName</key>
    <string>Blueprint</string>
    <key>CFBundleIdentifier</key>
    <string>com.specificlabs.blueprint-dev</string>
    <key>CFBundleVersion</key>
    <string>0.1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleExecutable</key>
    <string>blueprint-launcher</string>
    <key>CFBundleIconFile</key>
    <string>icon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

# ── Launcher script ──────────────────────────────────────────
# Strategy: the .app cannot directly access files in ~/Desktop due
# to macOS TCC sandbox restrictions. Instead, we:
#   1. Check if Blueprint is already running (curl doesn't need TCC)
#   2. If not, ask Terminal.app to run launch.sh — Terminal has FDA
#   3. Poll for services, then open the browser
#
# This means launch.sh always runs in Terminal.app's context with
# the user's full permissions, avoiding all sandbox issues.

LAUNCHER="$APP_DIR/Contents/MacOS/blueprint-launcher"

cat > "$LAUNCHER" << 'EOF_PART1'
#!/bin/bash
# Blueprint Dev Launcher
# Generated by make-dev-app.sh
# Delegates to Terminal.app to avoid macOS sandbox restrictions.

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

EOF_PART1

# Embed REPO_ROOT (needs build-time expansion)
echo "REPO_ROOT=\"$SCRIPT_DIR\"" >> "$LAUNCHER"

cat >> "$LAUNCHER" << 'EOF_PART2'

# ── Check if Blueprint is already running ─────────────────────
BACKEND_PORT=8000
FRONTEND_PORTS="4174 5173"

backend_up=false
running_frontend_port=""

if curl -s "http://127.0.0.1:$BACKEND_PORT/api/health" >/dev/null 2>&1; then
    backend_up=true
fi

for port in $FRONTEND_PORTS; do
    if curl -s "http://127.0.0.1:$port" >/dev/null 2>&1; then
        running_frontend_port="$port"
        break
    fi
done

if [ "$backend_up" = true ] && [ -n "$running_frontend_port" ]; then
    osascript -e 'display notification "Blueprint is already running — opening browser." with title "Blueprint"' 2>/dev/null || true
    open "http://localhost:$running_frontend_port"
    exit 0
fi

# ── Launch via Terminal.app ───────────────────────────────────
# Terminal.app has Full Disk Access and inherits the user's shell
# environment, so launch.sh can access ~/Desktop without issues.

osascript << ASCRIPT
tell application "Terminal"
    activate
    set blueprintRunning to false
    -- Check if there's an ACTIVE (busy) Blueprint tab
    repeat with w in windows
        repeat with t in tabs of w
            if busy of t and ((name of t contains "Blueprint") or (name of t contains "launch.sh")) then
                set blueprintRunning to true
                set selected of t to true
                set index of w to 1
            end if
        end repeat
    end repeat
    if not blueprintRunning then
        do script "cd \"$REPO_ROOT\" && bash launch.sh"
    end if
end tell
ASCRIPT

# ── Wait for services and open browser ────────────────────────
# Poll until both services respond, then open the browser.
FRONTEND_PORT=4174
opened=false
for i in $(seq 1 90); do
    if curl -s "http://127.0.0.1:$BACKEND_PORT/api/health" >/dev/null 2>&1 \
       && curl -s "http://127.0.0.1:$FRONTEND_PORT" >/dev/null 2>&1; then
        open "http://localhost:$FRONTEND_PORT"
        opened=true
        break
    fi
    sleep 1
done

if [ "$opened" = false ]; then
    osascript -e "display alert \"Blueprint Timeout\" message \"Services did not start within 90 seconds. Check the Terminal window for errors.\" as critical" 2>/dev/null
fi
EOF_PART2

chmod +x "$LAUNCHER"

# ── Copy icon ─────────────────────────────────────────────────

ICON_SRC="$SCRIPT_DIR/frontend/electron/icon.icns"
if [ -f "$ICON_SRC" ]; then
    cp "$ICON_SRC" "$APP_DIR/Contents/Resources/icon.icns"
    echo -e "${DIM}Icon copied from frontend/electron/icon.icns${NC}"
else
    echo -e "${DIM}Warning: icon.icns not found, app will use default icon${NC}"
fi

# ── Install to /Applications ─────────────────────────────────

echo -e "${CYAN}Installing to /Applications...${NC}"

if [ -d "/Applications/$APP_NAME.app" ]; then
    echo -e "${YELLOW}Replacing existing /Applications/$APP_NAME.app${NC}"
    rm -rf "/Applications/$APP_NAME.app"
fi

cp -R "$APP_DIR" "/Applications/$APP_NAME.app"

# Remove macOS quarantine so the app can launch without Gatekeeper blocking it
xattr -cr "/Applications/$APP_NAME.app" 2>/dev/null || true

# Flush macOS icon cache so the new icon shows immediately
touch "/Applications/$APP_NAME.app"
killall Finder 2>/dev/null || true

# Clean up local copy (the real one is in /Applications now)
rm -rf "$APP_DIR"

# ── Done ──────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}✔ Blueprint.app installed to /Applications!${NC}"
echo ""
echo -e "  ${CYAN}To launch:${NC}"
echo -e "    • Open ${GREEN}Blueprint${NC} from Launchpad, Spotlight, or Finder"
echo -e "    • Or drag it from /Applications to your ${GREEN}Dock${NC}"
echo ""
echo -e "  ${DIM}Logs visible in Terminal.app window${NC}"
echo -e "  ${DIM}Repo: $SCRIPT_DIR${NC}"
echo ""
