#!/bin/bash
# ──────────────────────────────────────────────────────────────
#  Generate Blueprint.app — a double-clickable macOS launcher
#  that wraps launch.sh so you never need to open a terminal.
#
#  Usage:  bash make-dev-app.sh
#  Result: Blueprint.app installed to /Applications
# ──────────────────────────────────────────────────────────────

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="Blueprint"
APP_DIR="$SCRIPT_DIR/$APP_NAME.app"

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
DIM='\033[0;90m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo -e "${CYAN}Creating $APP_NAME.app...${NC}"

# Clean previous build
rm -rf "$APP_DIR"

# Create .app directory structure
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

# ── Info.plist ────────────────────────────────────────────────

cat > "$APP_DIR/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Blueprint</string>
    <key>CFBundleDisplayName</key>
    <string>Blueprint</string>
    <key>CFBundleIdentifier</key>
    <string>com.specificlabs.blueprint-dev</string>
    <key>CFBundleVersion</key>
    <string>0.1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleExecutable</key>
    <string>blueprint-launcher</string>
    <key>CFBundleIconFile</key>
    <string>icon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSDesktopFolderUsageDescription</key>
    <string>Blueprint needs access to its project files on the Desktop.</string>
    <key>NSDocumentsFolderUsageDescription</key>
    <string>Blueprint needs access to project files.</string>
</dict>
</plist>
PLIST

# ── Launcher script ──────────────────────────────────────────
# The repo path is embedded at generation time so the .app works
# from anywhere — /Applications, Dock, Desktop, etc.
# Unlike the old design, this runs the repo's launch.sh directly
# via `bash` so updates to launch.sh take effect immediately
# without rebuilding the .app.

cat > "$APP_DIR/Contents/MacOS/blueprint-launcher" << LAUNCHER
#!/bin/bash
# Blueprint Dev Launcher
# Launched by macOS when you double-click Blueprint.app
# Generated by make-dev-app.sh — repo path embedded at build time.

# macOS GUI apps do NOT inherit your terminal PATH.
# We must set it up manually so python3 and node are found.
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\$PATH"

# Source shell profiles for any custom PATH additions
[ -f "\$HOME/.zprofile" ]     && source "\$HOME/.zprofile"     2>/dev/null || true
[ -f "\$HOME/.zshrc" ]        && source "\$HOME/.zshrc"        2>/dev/null || true
[ -f "\$HOME/.bash_profile" ] && source "\$HOME/.bash_profile" 2>/dev/null || true
[ -f "\$HOME/.profile" ]      && source "\$HOME/.profile"      2>/dev/null || true

# Absolute path to the Blueprint repo (embedded at generation time)
REPO_ROOT="$SCRIPT_DIR"
LAUNCH_SCRIPT="\$REPO_ROOT/launch.sh"

# ── Check if Blueprint is already running ─────────────────────
BACKEND_PORT=8000
FRONTEND_PORTS="4174 5173"

backend_up=false
running_frontend_port=""

if curl -s "http://127.0.0.1:\$BACKEND_PORT/api/health" >/dev/null 2>&1; then
    backend_up=true
fi

for port in \$FRONTEND_PORTS; do
    if curl -s "http://127.0.0.1:\$port" >/dev/null 2>&1; then
        running_frontend_port="\$port"
        break
    fi
done

if [ "\$backend_up" = true ] && [ -n "\$running_frontend_port" ]; then
    osascript -e 'display notification "Blueprint is already running — opening browser." with title "Blueprint"' 2>/dev/null || true
    open "http://localhost:\$running_frontend_port"
    exit 0
fi

# ── Validate launch.sh exists in repo ─────────────────────────
if [ ! -f "\$LAUNCH_SCRIPT" ]; then
    osascript -e "display alert \"Blueprint Error\" message \"Cannot find launch.sh at \$LAUNCH_SCRIPT. Is the repo still at this location?\" as critical" 2>/dev/null
    exit 1
fi

# ── Set up logging ────────────────────────────────────────────
LOG_DIR="\$HOME/.blueprint"
mkdir -p "\$LOG_DIR"
LOG_FILE="\$LOG_DIR/launch.log"

echo "" >> "\$LOG_FILE"
echo "──── Blueprint launched at \$(date) ────" >> "\$LOG_FILE"

# Show a notification that we're starting
osascript -e 'display notification "Starting backend and frontend..." with title "Blueprint" sound name "default"' 2>/dev/null || true

# ── Launch Blueprint ──────────────────────────────────────────
# Read launch.sh content and execute it inline to avoid macOS TCC
# "Operation not permitted" errors that block .app bundles from
# directly executing scripts in ~/Desktop or other protected folders.
# Updates to launch.sh still take effect without rebuilding the .app.
cd "\$REPO_ROOT"
export SCRIPT_DIR="\$REPO_ROOT"
/bin/bash -c "\$(cat "\$LAUNCH_SCRIPT")" >> "\$LOG_FILE" 2>&1 &
LAUNCH_PID=\$!

# ── Wait for services and open browser ────────────────────────
# launch.sh runs in the background; we poll until both services are
# up, then open the browser from the launcher process (not the
# redirected subprocess) so macOS always honours the open command.
FRONTEND_PORT=4174
opened=false
for i in \$(seq 1 60); do
    if curl -s "http://127.0.0.1:\$BACKEND_PORT/api/health" >/dev/null 2>&1 \
       && curl -s "http://127.0.0.1:\$FRONTEND_PORT" >/dev/null 2>&1; then
        open "http://localhost:\$FRONTEND_PORT"
        opened=true
        break
    fi
    sleep 1
done

if [ "\$opened" = false ]; then
    # Check if launch.sh already exited with an error
    if ! kill -0 "\$LAUNCH_PID" 2>/dev/null; then
        wait "\$LAUNCH_PID"
        EXIT_CODE=\$?
        if [ \$EXIT_CODE -ne 0 ]; then
            osascript -e "display alert \"Blueprint Failed\" message \"Blueprint exited with an error. Check the log at ~/.blueprint/launch.log for details.\" as critical" 2>/dev/null
        fi
        exit \$EXIT_CODE
    fi
fi

# ── Keep running until launch.sh exits ────────────────────────
wait "\$LAUNCH_PID"
EXIT_CODE=\$?

if [ \$EXIT_CODE -ne 0 ]; then
    osascript -e "display alert \"Blueprint Failed\" message \"Blueprint exited with an error. Check the log at ~/.blueprint/launch.log for details.\" as critical" 2>/dev/null
fi
LAUNCHER

chmod +x "$APP_DIR/Contents/MacOS/blueprint-launcher"

# ── Copy icon ─────────────────────────────────────────────────

ICON_SRC="$SCRIPT_DIR/frontend/electron/icon.icns"
if [ -f "$ICON_SRC" ]; then
    cp "$ICON_SRC" "$APP_DIR/Contents/Resources/icon.icns"
    echo -e "${DIM}Icon copied from frontend/electron/icon.icns${NC}"
else
    echo -e "${DIM}Warning: icon.icns not found, app will use default icon${NC}"
fi

# ── Install to /Applications ─────────────────────────────────

echo -e "${CYAN}Installing to /Applications...${NC}"

if [ -d "/Applications/$APP_NAME.app" ]; then
    echo -e "${YELLOW}Replacing existing /Applications/$APP_NAME.app${NC}"
    rm -rf "/Applications/$APP_NAME.app"
fi

cp -R "$APP_DIR" "/Applications/$APP_NAME.app"

# Remove macOS quarantine so the app can launch without Gatekeeper blocking it
xattr -cr "/Applications/$APP_NAME.app" 2>/dev/null || true

# Flush macOS icon cache so the new icon shows immediately
touch "/Applications/$APP_NAME.app"
killall Finder 2>/dev/null || true
killall Dock 2>/dev/null || true

# Clean up local copy (the real one is in /Applications now)
rm -rf "$APP_DIR"

# ── Done ──────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}✔ Blueprint.app installed to /Applications!${NC}"
echo ""
echo -e "  ${CYAN}To launch:${NC}"
echo -e "    • Open ${GREEN}Blueprint${NC} from Launchpad, Spotlight, or Finder"
echo -e "    • Or drag it from /Applications to your ${GREEN}Dock${NC}"
echo ""
echo -e "  ${DIM}Logs: ~/.blueprint/launch.log${NC}"
echo -e "  ${DIM}Repo: $SCRIPT_DIR${NC}"
echo ""
