"""Artifact Packager — package model and artifacts for distribution."""

import json
import os
import shutil
import time
from pathlib import Path


def run(ctx):
    package_start = time.time()
    model_input = ctx.load_input("model")
    include_readme = ctx.config.get("include_readme", True)
    compress = ctx.config.get("compress", True)
    output_dir = ctx.config.get("output_dir", "")

    # Resolve model path from various input types
    if isinstance(model_input, dict):
        model_path = model_input.get("path", "")
    elif isinstance(model_input, str):
        model_path = model_input
    else:
        model_path = ""

    if not output_dir:
        output_dir = os.path.join(ctx.run_dir, "package")

    os.makedirs(output_dir, exist_ok=True)
    ctx.log_message(f"Packaging to {output_dir}")
    ctx.report_progress(1, 4)

    # Copy model
    model_dest = os.path.join(output_dir, "model")
    if model_path and os.path.isdir(model_path):
        shutil.copytree(model_path, model_dest, dirs_exist_ok=True)
        ctx.log_message(f"Copied model directory: {model_path}")
    elif model_path and os.path.isfile(model_path):
        os.makedirs(model_dest, exist_ok=True)
        shutil.copy2(model_path, model_dest)
        ctx.log_message(f"Copied model file: {model_path}")
    elif isinstance(model_input, dict):
        # Save model metadata as JSON
        os.makedirs(model_dest, exist_ok=True)
        with open(os.path.join(model_dest, "model_info.json"), "w") as f:
            json.dump(model_input, f, indent=2, default=str)
        ctx.log_message("Saved model metadata (no local model files)")
    ctx.report_progress(2, 4)

    # Try to get metrics
    metrics = None
    try:
        metrics = ctx.load_input("metrics")
        with open(os.path.join(output_dir, "metrics.json"), "w") as f:
            json.dump(metrics, f, indent=2, default=str)
    except (ValueError, KeyError):
        pass

    # README — use custom README from input if connected, otherwise auto-generate
    custom_readme = None
    try:
        custom_readme = ctx.load_input("readme")
    except (ValueError, KeyError):
        pass

    if custom_readme and isinstance(custom_readme, str):
        # Use custom README content (e.g. from Model Card Writer)
        readme_content = custom_readme
        # If it's a file path, read it
        if os.path.isfile(custom_readme):
            with open(custom_readme, "r", encoding="utf-8") as f:
                readme_content = f.read()
        with open(os.path.join(output_dir, "README.md"), "w", encoding="utf-8") as f:
            f.write(readme_content)
        ctx.log_message("Used custom README from input port")
    elif include_readme:
        lines = ["# Model Package\n", "Generated by Blueprint\n"]
        if isinstance(model_input, dict):
            model_name = model_input.get("model_name", model_input.get("model_id", ""))
            if model_name:
                lines.append(f"## Model: {model_name}\n")
            method = model_input.get("method", "")
            source = model_input.get("source", "")
            if method:
                lines.append(f"- **Method:** {method}")
            if source:
                lines.append(f"- **Source:** {source}")
            base = model_input.get("base_model", model_input.get("model_id", ""))
            if base and base != model_name:
                lines.append(f"- **Base model:** {base}")
            quant = model_input.get("quantization") or model_input.get("bits")
            if quant:
                lines.append(f"- **Quantization:** {quant}")
        if metrics and isinstance(metrics, dict):
            lines.append("\n## Metrics\n")
            lines.append("| Metric | Value |")
            lines.append("|--------|-------|")
            for k, v in sorted(metrics.items()):
                if isinstance(v, float):
                    lines.append(f"| {k} | {v:.4f} |")
                elif isinstance(v, (int, str, bool)):
                    lines.append(f"| {k} | {v} |")
        lines.append(f"\n---\n*Packaged with Blueprint*")
        with open(os.path.join(output_dir, "README.md"), "w") as f:
            f.write("\n".join(lines))
    ctx.report_progress(3, 4)

    # Compress to tar.gz if requested
    final_output = output_dir
    if compress:
        archive_base = output_dir.rstrip("/")
        try:
            archive_path = shutil.make_archive(archive_base, "gztar", root_dir=os.path.dirname(output_dir), base_dir=os.path.basename(output_dir))
            ctx.log_message(f"Compressed to: {archive_path}")
            final_output = archive_path
        except Exception as e:
            ctx.log_message(f"WARNING: Compression failed ({e}), using uncompressed output")

    package_time = time.time() - package_start
    artifact_files = list(Path(output_dir).rglob("*"))
    artifact_count = sum(1 for f in artifact_files if f.is_file())
    total_size = sum(f.stat().st_size for f in artifact_files if f.is_file())
    ctx.log_metric("artifact_count", artifact_count)
    ctx.log_metric("total_size_bytes", total_size)
    ctx.log_metric("package_time_s", round(package_time, 3))

    ctx.log_message("Package complete")
    ctx.report_progress(4, 4)
    ctx.save_output("artifact", final_output)
    ctx.save_artifact("package", output_dir)
