"""Leaderboard Publisher — format evaluation results as a leaderboard table."""

import json
import os
import time


def run(ctx):
    title = ctx.config.get("title", "Model Leaderboard")
    sort_by = ctx.config.get("sort_by", "")
    sort_order = ctx.config.get("sort_order", "descending")
    output_format = ctx.config.get("format", "markdown")

    # Collect all metrics inputs
    all_entries = []

    for input_name in ["metrics", "dataset", "input", "results",
                        "metrics_1", "metrics_2", "metrics_3", "metrics_4"]:
        try:
            data = ctx.load_input(input_name)
            if isinstance(data, str) and os.path.isdir(data):
                data_file = os.path.join(data, "data.json")
                if os.path.isfile(data_file):
                    with open(data_file, "r") as f:
                        data = json.load(f)
            elif isinstance(data, str) and os.path.isfile(data):
                with open(data, "r") as f:
                    data = json.load(f)

            if isinstance(data, list):
                all_entries.extend(data)
            elif isinstance(data, dict):
                all_entries.append(data)
        except (ValueError, Exception):
            pass

    if not all_entries:
        ctx.log_message("No data connected. Generating demo leaderboard.")
        all_entries = [
            {"model": "Llama-3-70B", "mmlu": 0.82, "humaneval": 0.68, "hellaswag": 0.87, "average": 0.79},
            {"model": "Mistral-7B-v0.3", "mmlu": 0.64, "humaneval": 0.45, "hellaswag": 0.81, "average": 0.63},
            {"model": "Phi-3-mini", "mmlu": 0.69, "humaneval": 0.52, "hellaswag": 0.78, "average": 0.66},
            {"model": "Qwen-2-7B", "mmlu": 0.71, "humaneval": 0.58, "hellaswag": 0.80, "average": 0.70},
            {"model": "Gemma-2-9B", "mmlu": 0.73, "humaneval": 0.55, "hellaswag": 0.83, "average": 0.70},
        ]

    ctx.log_message(f"Building leaderboard: {len(all_entries)} entries")

    # Determine columns
    if all_entries and isinstance(all_entries[0], dict):
        all_keys = set()
        for entry in all_entries:
            all_keys.update(entry.keys())
        # Filter out non-displayable columns
        columns = sorted([k for k in all_keys if not k.startswith("_")])
    else:
        columns = ["value"]
        all_entries = [{"value": str(e)} for e in all_entries]

    # Sort entries
    if sort_by and sort_by in columns:
        reverse = sort_order == "descending"
        try:
            all_entries.sort(key=lambda x: float(x.get(sort_by, 0)), reverse=reverse)
        except (ValueError, TypeError):
            all_entries.sort(key=lambda x: str(x.get(sort_by, "")), reverse=reverse)
    elif not sort_by:
        # Try to sort by "average" or first numeric column
        for col in ["average", "score", "accuracy", "mmlu", "f1"]:
            if col in columns:
                sort_by = col
                try:
                    all_entries.sort(key=lambda x: float(x.get(col, 0)), reverse=True)
                except (ValueError, TypeError):
                    pass
                break

    # Add rank
    for i, entry in enumerate(all_entries):
        entry["rank"] = i + 1

    # Format output
    if output_format == "markdown":
        lines = []
        lines.append(f"# {title}")
        lines.append("")
        lines.append(f"*Updated: {time.strftime('%Y-%m-%d %H:%M:%S')}*")
        if sort_by:
            lines.append(f"*Sorted by: {sort_by} ({sort_order})*")
        lines.append("")

        display_cols = ["rank"] + [c for c in columns if c != "rank"]
        lines.append("| " + " | ".join(display_cols) + " |")
        lines.append("| " + " | ".join(["---"] * len(display_cols)) + " |")

        for entry in all_entries:
            vals = []
            for col in display_cols:
                v = entry.get(col, "")
                if isinstance(v, float):
                    vals.append(f"{v:.4f}")
                else:
                    vals.append(str(v)[:40])
            lines.append("| " + " | ".join(vals) + " |")

        lines.append("")
        lines.append("---")
        lines.append("*Generated by Blueprint Leaderboard Publisher*")
        content = "\n".join(lines)
        ext = "md"

    elif output_format == "csv":
        display_cols = ["rank"] + [c for c in columns if c != "rank"]
        lines = [",".join(display_cols)]
        for entry in all_entries:
            vals = [str(entry.get(c, "")) for c in display_cols]
            lines.append(",".join(vals))
        content = "\n".join(lines)
        ext = "csv"

    else:  # json
        content = json.dumps(all_entries, indent=2, default=str)
        ext = "json"

    # Save
    out_dir = os.path.join(ctx.run_dir, "leaderboard")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"leaderboard.{ext}")
    with open(out_path, "w") as f:
        f.write(content)

    ctx.save_output("artifact", out_dir)
    ctx.save_output("metrics", {
        "num_entries": len(all_entries),
        "num_columns": len(columns),
        "sort_by": sort_by or "none",
        "format": output_format,
    })
    ctx.log_metric("num_entries", len(all_entries))
    ctx.log_message(f"Leaderboard published: {len(all_entries)} entries, {output_format} format")
    ctx.report_progress(1, 1)
