"""initial schema

Revision ID: 86d04226c57a
Revises: 
Create Date: 2026-03-06 14:14:08.324404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d04226c57a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_heartbeat', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint_runs', schema=None) as batch_op:
        batch_op.drop_column('last_heartbeat')

    # ### end Alembic commands ###
