#!/usr/bin/env python3
"""Generate frontend/src/lib/generated/model-catalog.generated.ts from docs/MODEL_CATALOG.yaml.

Usage:
    python scripts/generate_model_catalog.py
    python scripts/generate_model_catalog.py --check  # CI: verify freshness
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
YAML_PATH = PROJECT_ROOT / "docs" / "MODEL_CATALOG.yaml"
OUTPUT_PATH = PROJECT_ROOT / "frontend" / "src" / "lib" / "generated" / "model-catalog.generated.ts"


def generate() -> str:
    """Read MODEL_CATALOG.yaml and produce a TypeScript module string."""
    with open(YAML_PATH, "r") as f:
        data = yaml.safe_load(f) or {}

    families = data.get("families", [])
    heuristics = data.get("heuristic_patterns", [])

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by scripts/generate_model_catalog.py")
    lines.append("// Source: docs/MODEL_CATALOG.yaml")
    lines.append("// Do NOT edit by hand.\n")

    lines.append("export interface ModelFamilyEntry {")
    lines.append("  pattern: RegExp")
    lines.append("  aliases: string[]")
    lines.append("  params_b: number")
    lines.append("  context: number | null")
    lines.append("}\n")

    lines.append("export interface HeuristicEntry {")
    lines.append("  pattern: RegExp")
    lines.append("  unit: 'B' | 'M'")
    lines.append("}\n")

    lines.append("export const MODEL_FAMILIES: ModelFamilyEntry[] = [")
    for entry in families:
        pattern = entry.get("pattern", "")
        aliases = entry.get("aliases", [])
        params_b = entry.get("params_b", 0)
        context = entry.get("context")
        # Escape backslashes for JS regex
        js_pattern = pattern
        aliases_str = ", ".join(f"'{a}'" for a in aliases)
        ctx_str = str(context) if context is not None else "null"
        lines.append(f"  {{ pattern: /{js_pattern}/i, aliases: [{aliases_str}], params_b: {params_b}, context: {ctx_str} }},")
    lines.append("]\n")

    lines.append("export const HEURISTIC_PATTERNS: HeuristicEntry[] = [")
    for entry in heuristics:
        pattern = entry.get("pattern", "")
        unit = entry.get("unit", "B")
        lines.append(f"  {{ pattern: /{pattern}/i, unit: '{unit}' }},")
    lines.append("]\n")

    # Normalizer function
    lines.append("/** Normalize a model name for matching (lowercase, replace /_.  with -). */")
    lines.append("export function normalizeModelName(name: string): string {")
    lines.append("  return name.toLowerCase().replace(/[\\/_.]/g, '-')")
    lines.append("}\n")

    lines.append("export interface ModelInfo {")
    lines.append("  params_b: number")
    lines.append("  context: number | null")
    lines.append("  source: 'catalog' | 'heuristic' | 'config'")
    lines.append("}\n")

    lines.append("/**")
    lines.append(" * Look up model intelligence by name.")
    lines.append(" * Resolution: regex match → alias substring → heuristic extraction → null.")
    lines.append(" */")
    lines.append("export function lookupModel(rawName: string): ModelInfo | null {")
    lines.append("  if (!rawName) return null")
    lines.append("  const name = normalizeModelName(rawName)\n")
    lines.append("  // 1. Regex pattern match (first match wins)")
    lines.append("  for (const fam of MODEL_FAMILIES) {")
    lines.append("    if (fam.pattern.test(name)) {")
    lines.append("      return { params_b: fam.params_b, context: fam.context, source: 'catalog' }")
    lines.append("    }")
    lines.append("  }\n")
    lines.append("  // 2. Alias substring match")
    lines.append("  for (const fam of MODEL_FAMILIES) {")
    lines.append("    for (const alias of fam.aliases) {")
    lines.append("      if (name.includes(alias)) {")
    lines.append("        return { params_b: fam.params_b, context: fam.context, source: 'catalog' }")
    lines.append("      }")
    lines.append("    }")
    lines.append("  }\n")
    lines.append("  // 3. Heuristic extraction")
    lines.append("  for (const h of HEURISTIC_PATTERNS) {")
    lines.append("    const m = name.match(h.pattern)")
    lines.append("    if (m) {")
    lines.append("      let val = parseFloat(m[1])")
    lines.append("      if (h.unit === 'M') val /= 1000")
    lines.append("      if (val > 0) return { params_b: val, context: null, source: 'heuristic' }")
    lines.append("    }")
    lines.append("  }\n")
    lines.append("  return null")
    lines.append("}")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate model catalog TypeScript")
    parser.add_argument("--check", action="store_true", help="Verify generated file is up-to-date")
    args = parser.parse_args()

    content = generate()

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"MISSING: {OUTPUT_PATH}")
            sys.exit(1)
        existing = OUTPUT_PATH.read_text()
        if existing == content:
            print("OK: model-catalog.generated.ts is up-to-date")
        else:
            print(f"STALE: {OUTPUT_PATH}")
            print("Run: python scripts/generate_model_catalog.py")
            sys.exit(1)
    else:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(content)
        families_count = content.count("pattern: /")
        print(f"Generated {OUTPUT_PATH.relative_to(PROJECT_ROOT)} ({families_count} entries)")


if __name__ == "__main__":
    main()
