#!/usr/bin/env python3
"""
Print a human-readable summary of the contract matrix test snapshots.

Usage:
    python scripts/print_contract_matrix.py

Reads the snapshot files generated by test_contract_matrix.py and prints
a formatted summary table.
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SNAPSHOT_DIR = REPO_ROOT / "backend" / "tests" / "fixtures" / "contracts" / "__snapshots__"


def load_snapshots() -> dict:
    snapshots = {}
    if not SNAPSHOT_DIR.exists():
        return snapshots
    for path in sorted(SNAPSHOT_DIR.glob("*.snapshot.json")):
        with open(path) as f:
            snapshots[path.stem.replace(".snapshot", "")] = json.load(f)
    return snapshots


def print_matrix(snapshots: dict) -> None:
    if not snapshots:
        print("No snapshots found. Run tests first:")
        print("  python -m pytest backend/tests/test_contract_matrix.py -v")
        return

    # Header
    print("=" * 90)
    print("CONTRACT MATRIX — Current Backend Behavior Snapshots")
    print("=" * 90)
    print()

    for name, snap in snapshots.items():
        print(f"--- {name} ---")
        print()

        # Topological sort
        topo = snap.get("topological_sort", {})
        if "error" in topo:
            print(f"  Topo Sort:    ERROR: {topo['error']}")
        else:
            order = topo.get("order", [])
            all_inc = topo.get("all_nodes_included", False)
            status = "COMPLETE" if all_inc else f"INCOMPLETE ({topo.get('node_count', '?')}/{len(order)})"
            print(f"  Topo Sort:    {' → '.join(order) if order else '(empty)'} [{status}]")

        # Loop detection
        loops = snap.get("loop_detection", {})
        if "error" in loops:
            print(f"  Loop Detect:  ERROR ({loops.get('error_type', '?')}): {loops['error']}")
        else:
            count = loops.get("loop_count", 0)
            if count > 0:
                for lp in loops.get("loops", []):
                    print(f"  Loop Detect:  {count} loop(s) — controller={lp['controller_id']}, body={lp['body_node_ids']}")
            else:
                print(f"  Loop Detect:  No loops")

        # Validation
        val = snap.get("validation", {})
        if "error" in val:
            print(f"  Validation:   ERROR: {val['error']}")
        else:
            status = "VALID" if val.get("valid") else "INVALID"
            errs = val.get("error_count", 0)
            warns = val.get("warning_count", 0)
            print(f"  Validation:   {status} ({errs} errors, {warns} warnings)")
            for err in val.get("errors", [])[:3]:
                print(f"                  - {err}")

        # Compiler
        comp = snap.get("compiler", {})
        if comp.get("generated"):
            print(f"  Compiler:     GENERATED ({comp.get('code_length', '?')} chars)")
        else:
            print(f"  Compiler:     REFUSED: {comp.get('error', '?')}")

        # Partial rerun safety
        pr = snap.get("partial_rerun_safety", {})
        safe = "SAFE" if pr.get("safe_per_contract") else "UNSAFE"
        reason = ""
        if pr.get("has_loop_controller"):
            reason = " (has loop controller)"
        print(f"  Partial Rerun: {safe}{reason}")

        # Port compat (if present)
        pc = snap.get("port_compat", {})
        if pc:
            print(f"  Port Compat:")
            for k, v in sorted(pc.items()):
                status = "ALLOWED" if v else "BLOCKED"
                print(f"    {k:>20s}: {status}")

        # Handle resolution (if present)
        hr = snap.get("handle_resolution", {})
        if hr:
            print(f"  Handle Resolution:")
            for eid, info in hr.items():
                changed = "RESOLVED" if info.get("changed") else "unchanged"
                print(f"    {eid}: {info['original']} → {info['resolved']} [{changed}]")

        print()

    # Summary table
    print("=" * 90)
    print("SUMMARY TABLE")
    print("=" * 90)
    print()
    header = f"{'Fixture':<30s} {'Valid?':<8s} {'Cycles?':<10s} {'Loops':<8s} {'Compiler':<12s} {'Partial':<10s}"
    print(header)
    print("-" * len(header))

    for name, snap in snapshots.items():
        val = snap.get("validation", {})
        valid = "YES" if val.get("valid") else "NO"
        has_cycle = "YES" if any("cycle" in e.lower() for e in val.get("errors", [])) else "NO"
        loop_count = snap.get("loop_detection", {}).get("loop_count", "ERR")
        if "error" in snap.get("loop_detection", {}):
            loop_count = "ERR"
        compiler = "YES" if snap.get("compiler", {}).get("generated") else "NO"
        partial = "SAFE" if snap.get("partial_rerun_safety", {}).get("safe_per_contract") else "UNSAFE"
        print(f"{name:<30s} {valid:<8s} {str(has_cycle):<10s} {str(loop_count):<8s} {compiler:<12s} {partial:<10s}")

    print()


def main():
    snapshots = load_snapshots()
    print_matrix(snapshots)


if __name__ == "__main__":
    main()
